version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slack-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-joa18njjc9yr"
s3_prefix = "slack-app"
region = "ap-northeast-1"
profile = "taniyama"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
