AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-todo-app

Resources:
  Challenge:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: challenge
      CodeUri: challenge/
      Handler: app.handler
      Runtime: nodejs16.x
      Role: arn:aws:iam::907081723216:role/SamDeployRole
      Architectures:
        - arm64
      Environment:
        Variables:
          TZ: Asia/Tokyo
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
      Events:
        ChallengeApi:
          Type: Api
          Properties:
            Path: /challenge
            Method: post
            RestApiId: !Ref SlackTodoApi

  SlackTodoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: slack-todo-api
      EndpointConfiguration:
        Type: REGIONAL
      StageName: prod
  # SlackTodoApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: Prod
  #     DefinitionBody:
  #       swagger: '2.0'
  #       info:
  #         title: My API
  #         version: '1.0'
  #       paths:
  #         /slack-todo-api:
  #           post:
  #             x-amazon-apigateway-integration:
  #               type: aws_proxy
  #               uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/*/functions/${Challenge.Arn}/invocations
  #               httpMethod: "POST"
